Repository TomIA24/unow-back, pull requests merged in 2024-10, with the labels that each got.

#14 Feat/add onboard
  models/Trainer.js
  routes/trainerControle.js
Labels: bug, enhancement

#18 Feat/update trainer notification
  routes/CandidatControle.js
  routes/CategoryControle.js
  routes/trainerControle.js
Labels: bug

#19 fix the attributes to match between the backend and frontend
  models/Trainer.js
Labels: bug

#22 Feat/add get trainer and courses trainer
  .env
  models/Training.js
  models/course.js
  routes/courseControle.js
  routes/trainingControle.js
Labels: enhancement

#23 Feat/add relation programs and category
  controllers/programController.js
  models/Program.js
  routes/userControle.js
Labels: enhancement

#25 Feat/calendar trainer
  controllers/calendarEventController.js
  models/CalendarEvent.js
  models/Trainer.js
  routes/calendarEventRoute.js
  server.js
Labels: enhancement

#26 Fix/handle unavailablity in training events
  .env
  controllers/calendarEventController.js
  models/CalendarEvent.js
  package-lock.json
  package.json
  services/calendarService.js
  utils/dateUtils.js
Labels: enhancement

#27 Add/currency actu
  .env
  models/TrainerNotifications.js
Labels: enhancement

#29 Add/cart order
  controllers/cartController.js
  controllers/orderController.js
  models/Cart.js
  models/Order.js
  routes/cartRoute.js
  routes/orderRoute.js
  server.js
  services/orderService.js
Labels: bug, enhancement

#34 Dev trainer credentials
  models/Trainer.js
  routes/emailSender.js
  routes/trainerControle.js
Labels: enhancement
